name: chess_board_widget
description: A chess board widget.

version: 0.1.0+6

repository: https://github.com/bedardjo/chess_board.git

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.2
  chess_lib: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_board/
